name = "purrsafe-landing"
compatibility_date = "2026-09-29"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "purrsafe-beta"
database_id = "cca9d9b1-9716-4356-a587-e77db40f67dd"
migrations_dir = "migrations"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[vars]
PUBLIC_SITE_URL = "https://pursafe.selenasolutions.com"
